version: "3.9"

services:

  frontend:
    build: ./frontend
    ports:
      - "3000:3000"
    volumes:
      - ./frontend/:/app
    
    networks:
      - mynetwork
    
  
  # backend:
  #   build: ./backend
  #   volumes:
  #     - ./backend:/app
  #   ports:
  #     - "5000:5000"
    
  #   networks:
  #     - mynetwork


# criando rede
networks:
  mynetwork: